services:
  - type: web
    name: pdf-image-converter-api
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev && \
      pip install --upgrade pip setuptools wheel && \
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        generateValue: true
    disk:
      name: temp-storage
      mountPath: /tmp
      sizeGB: 1
